# Generated by Django 5.0.2 on 2026-07-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_add_job_category_and_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_reopened', 'Job Reopened'), ('draft_saved', 'Draft Saved'), ('draft_deleted', 'Draft Deleted')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='jobs.jobposting')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Activity',
                'verbose_name_plural': 'Recruiter Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
