# Generated by Django 4.2 on 2026-08-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
    ]
