# Generated by Django 4.2 on 2026-08-11 03:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='resumes/%Y/%m/'),
        ),
    ]
