# Generated by Django 5.0.2 on 2026-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_model_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education_required',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
