# Generated by Django 4.2 on 2026-08-02 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('results', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('ai_match', 'AI Job Match upload'), ('profile', 'Profile CV')], default='ai_match', max_length=20)),
                ('cv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('profession', models.CharField(blank=True, default='', max_length=120)),
                ('specialization', models.CharField(blank=True, default='', max_length=120)),
                ('career_level', models.CharField(blank=True, default='', max_length=20)),
                ('match_score', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis Session',
                'verbose_name_plural': 'AI Analysis Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UIState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UI State',
                'verbose_name_plural': 'UI States',
                'ordering': ['key'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
