# Generated by Django 4.2 on 2026-08-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=180)),
                ('resume_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='ready', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('improvement_plan', models.JSONField(blank=True, default=dict)),
                ('readiness', models.JSONField(blank=True, default=dict)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('hr_score', models.PositiveIntegerField(default=0)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('improvement_plan', models.JSONField(blank=True, default=list)),
                ('recommended_courses', models.JSONField(blank=True, default=list)),
                ('next_topics', models.JSONField(blank=True, default=list)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='chatbot.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Report',
                'verbose_name_plural': 'Interview Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('difficulty', models.CharField(blank=True, default='', max_length=20)),
                ('answer', models.TextField(blank=True, default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('better_answer', models.TextField(blank=True, default='')),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chatbot.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Turn',
                'verbose_name_plural': 'Interview Turns',
                'ordering': ['question_index', 'id'],
                'unique_together': {('session', 'question_index')},
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', 'is_active'], name='idx_interview_user_active'),
        ),
    ]
