# Generated by Django 4.2 on 2026-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_interviewsession_interviewreport_interviewturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
