# Generated by Django 4.2 on 2026-08-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_intent_conversation_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreport',
            name='behavioral_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='coaching',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
