# Generated by Django 4.2 on 2026-07-31 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('career_level', models.CharField(blank=True, default='', max_length=20)),
                ('resume_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Roadmap',
                'verbose_name_plural': 'Learning Roadmaps',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'resume_hash')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('skill_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='skillgap.learningroadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_step_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roadmap Step Progress',
                'verbose_name_plural': 'Roadmap Step Progress',
                'ordering': ['step_number'],
                'unique_together': {('roadmap', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('career_level', models.CharField(blank=True, default='', max_length=20)),
                ('resume_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Recommendation',
                'verbose_name_plural': 'Course Recommendations',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'resume_hash')},
            },
        ),
    ]
