import json

from django.conf import settings

from apps.shared.profession_classifier import PROFESSION_CONFIGS
from apps.shared.skill_normalizer import display_name, normalize_skill

DIFFICULTY_RANK = {"beginner": 1, "intermediate": 2, "advanced": 3}
JUNIOR_MAX = "intermediate"

SKILL_FAMILY_ALIASES = {
    "restapi": "rest",
    "restapis": "rest",
    "restfulapi": "rest",
    "apidevelopment": "rest",
    "apidesign": "rest",
}

SKILL_DEPENDENCIES = {
    "typescript": ["javascript"],
    "react": ["javascript", "html", "css"],
    "next.js": ["react", "javascript"],
    "vue.js": ["javascript", "html", "css"],
    "angular": ["typescript", "javascript"],
    "redux": ["react"],
    "tailwindcss": ["html", "css"],
    "scss": ["css"],
    "graphql": ["javascript", "rest"],
    "webpack": ["javascript"],
    "vite": ["javascript"],
    "bootstrap": ["html", "css"],
    "responsivedesign": ["html", "css"],
    "reactnative": ["react", "javascript"],
    "flutter": ["dart"],
    "swiftui": ["swift"],
    "uikit": ["swift"],
    "kotlin": ["java"],
    "android": ["kotlin", "java"],
    "ios": ["swift"],
    "appstore": ["ios"],
    "mobileui": ["flutter", "reactnative"],
    "mobilearchitecture": ["flutter", "reactnative"],
    "django": ["python"],
    "djangorestframework": ["django", "python"],
    "fastapi": ["python"],
    "flask": ["python"],
    "node.js": ["javascript"],
    "express": ["node.js", "javascript"],
    "springboot": ["java"],
    "celery": ["django", "python"],
    "postgresql": ["sql"],
    "mysql": ["sql"],
    "mongodb": ["sql"],
    "restapis": ["rest"],
    "apidesign": ["rest"],
    "microservices": ["docker", "restapis"],
    "kubernetes": ["docker"],
    "helm": ["kubernetes", "docker"],
    "terraform": ["aws"],
    "ansible": ["linux"],
    "jenkins": ["git", "docker"],
    "cicd": ["git", "docker"],
    "githubactions": ["git"],
    "prometheus": ["linux"],
    "grafana": ["prometheus", "linux"],
    "elkstack": ["linux"],
    "shellscripting": ["linux"],
    "machinelearning": ["python", "statistics"],
    "deeplearning": ["machinelearning", "python"],
    "tensorflow": ["machinelearning", "python"],
    "pytorch": ["machinelearning", "python"],
    "keras": ["machinelearning", "python"],
    "scikitlearn": ["machinelearning", "python"],
    "nlp": ["machinelearning", "python"],
    "computervision": ["deeplearning", "machinelearning"],
    "llm": ["machinelearning", "python"],
    "faiss": ["python", "nlp"],
    "mlops": ["docker", "machinelearning", "cicd"],
    "modeldeployment": ["mlops", "machinelearning"],
    "pandas": ["python"],
    "numpy": ["python"],
    "matplotlib": ["python", "numpy"],
    "seaborn": ["python", "matplotlib"],
    "statistics": ["python"],
    "probability": ["statistics"],
    "featureengineering": ["machinelearning", "pandas"],
    "abtesting": ["statistics", "python"],
    "datavisualization": ["python", "pandas"],
    "etl": ["sql", "python"],
    "airflow": ["python", "etl"],
    "spark": ["python", "sql"],
    "hadoop": ["spark", "java"],
    "kafka": ["python"],
    "datamodeling": ["sql"],
    "snowflake": ["etl", "sql"],
    "bigquery": ["sql", "gcp"],
    "redshift": ["sql", "aws"],
    "datapipeline": ["etl", "python"],
    "datawarehouse": ["etl", "sql", "datamodeling"],
    "tableau": ["sql"],
    "powerbi": ["sql", "excel"],
    "datacleaning": ["python", "pandas"],
    "dashboarding": ["powerbi", "tableau"],
    "reporting": ["sql", "dashboarding"],
    "dataanalysis": ["excel", "sql"],
    "looker": ["sql"],
    "datastructures": ["python"],
    "algorithms": ["datastructures"],
    "systemdesign": ["microservices", "algorithms"],
    "oop": ["python"],
    "designpatterns": ["oop"],
    "tdd": ["git", "python"],
    "dotnet": ["csharp"],
    "scala": ["java"],
    "quickbooks": ["bookkeeping"],
    "xero": ["bookkeeping"],
    "taxpreparation": ["accounting"],
    "financialreporting": ["accounting"],
    "gaap": ["accounting"],
    "auditing": ["accounting"],
    "bookkeeping": ["accounting"],
    "financialanalysis": ["accounting", "excel"],
    "erp": ["accounting"],
    "sap": ["erp"],
    "oraclefinancials": ["erp"],
    "onboarding": ["recruiting"],
    "employeerelations": ["hrpolicies"],
    "benefitsadministration": ["payroll"],
    "laborlaws": ["hrpolicies"],
    "talentacquisition": ["recruiting"],
    "ats": ["recruiting"],
    "networksecurity": ["linux"],
    "firewall": ["networksecurity"],
    "idsips": ["networksecurity"],
    "penetrationtesting": ["networksecurity", "linux"],
    "ethicalhacking": ["networksecurity"],
    "siem": ["networksecurity"],
    "riskassessment": ["networksecurity"],
    "compliance": ["riskassessment"],
    "cissp": ["networksecurity"],
    "cryptography": ["python"],
    "securityauditing": ["networksecurity"],
    "seo": ["digitalmarketing"],
    "sem": ["digitalmarketing"],
    "contentstrategy": ["digitalmarketing"],
    "socialmedia": ["digitalmarketing"],
    "googleanalytics": ["digitalmarketing"],
    "emailmarketing": ["digitalmarketing"],
    "marketingautomation": ["emailmarketing", "crm"],
    "hubspot": ["crm"],
    "growthstrategy": ["digitalmarketing"],
    "campaignmanagement": ["digitalmarketing"],
    "brandstrategy": ["contentstrategy"],
    "roadmapping": ["productstrategy"],
    "wireframing": ["userresearch"],
    "prototyping": ["wireframing"],
    "usabilitytesting": ["prototyping", "userresearch"],
    "interactiondesign": ["uidesign"],
    "informationarchitecture": ["userresearch"],
    "designsystems": ["prototyping", "figma"],
    "userflows": ["wireframing"],
    "personas": ["userresearch"],
    "uidesign": ["figma"],
    "uxdesign": ["uidesign", "userresearch"],
    "branding": ["illustrator"],
    "visualdesign": ["colortheory", "typography"],
    "logos": ["illustrator", "branding"],
    "printdesign": ["illustrator", "indesign"],
    "adobecreativesuite": ["photoshop", "illustrator"],
    "layout": ["typography"],
    "scrum": ["agile"],
    "jira": ["agile"],
    "stakeholdermanagement": ["communication"],
    "productmetrics": ["excel", "dataanalysis"],
    "teamwork": ["communication"],
    "collaboration": ["communication"],
    "emotionalintelligence": ["communication"],
    "postman": ["restapis"],
    "riverpod": ["flutter"],
    "restfulapi": ["rest"],
    "restapi": ["rest"],
    "apidevelopment": ["rest"],
    "versioncontrol": ["git"],
    "mobiletesting": ["mobileui"],
    "git": [],
    "docker": [],
    "sql": [],
    "rest": [],
    "apis": ["rest"],
    "html": [],
    "css": [],
    "python": [],
    "java": [],
    "javascript": [],
    "excel": [],
    "linux": [],
    "aws": [],
    "azure": [],
    "gcp": [],
    "communication": [],
    "leadership": [],
    "problemsolving": [],
    "timemanagement": [],
    "criticalthinking": [],
    "adaptability": [],
    "creativity": [],
    "agile": [],
    "accounting": [],
    "payroll": [],
    "recruiting": [],
    "hrpolicies": [],
    "hris": [],
    "performancemanagement": [],
    "digitalmarketing": [],
    "crm": [],
    "productstrategy": [],
    "userresearch": [],
    "figma": [],
    "sketch": [],
    "adobexd": [],
    "photoshop": [],
    "illustrator": [],
    "indesign": [],
    "typography": [],
    "colortheory": [],
    "canva": [],
    "confluence": [],
    "notion": [],
    "slack": [],
    "yaml": [],
    "cplusplus": [],
    "csharp": [],
    "go": [],
    "rust": [],
    "ruby": [],
    "swift": [],
    "dart": [],
    "firebase": [],
    "vscode": [],
}

DIFFICULTY_OVERRIDES = {
    "kubernetes": "advanced",
    "helm": "advanced",
    "systemdesign": "advanced",
    "deeplearning": "advanced",
    "computervision": "advanced",
    "mlops": "advanced",
    "modeldeployment": "advanced",
    "microservices": "advanced",
    "spark": "advanced",
    "datawarehouse": "advanced",
    "datapipeline": "advanced",
    "penetrationtesting": "advanced",
    "ethicalhacking": "advanced",
    "cissp": "advanced",
    "kafka": "advanced",
    "mobilearchitecture": "advanced",
}

DEFAULT_DIFFICULTY = "beginner"
BASE_HOURS = {"beginner": 8, "intermediate": 16, "advanced": 28}

# Friendly display names for catalog keys not present in any profession config.
DISPLAY_OVERRIDES = {
    "cleanarchitecture": "Clean Architecture",
    "unittesting": "Unit Testing",
    "fluttertesting": "Flutter Testing",
    "responsivewebdesign": "Responsive Web Design",
    "mobiletesting": "Mobile Testing",
    "apidesign": "API Design",
}

# Technology families used to keep recommendations relevant to the
# candidate's detected stack (a Flutter developer must never be recommended
# Swift or iOS courses, even when related-profession jobs list them).
SKILL_FAMILIES = {
    "flutter": "cross_platform_mobile",
    "dart": "cross_platform_mobile",
    "reactnative": "cross_platform_mobile",
    "firebase": "cross_platform_mobile",
    "riverpod": "cross_platform_mobile",
    "provider": "cross_platform_mobile",
    "sqlite": "cross_platform_mobile",
    "mobileui": "cross_platform_mobile",
    "mobilearchitecture": "cross_platform_mobile",
    "mobiletesting": "cross_platform_mobile",
    "fluttertesting": "cross_platform_mobile",
    "flutterdeployment": "cross_platform_mobile",
    "kotlin": "native_android",
    "android": "native_android",
    "materialdesign": "native_android",
    "jetpackcompose": "native_android",
    "coroutines": "native_android",
    "swift": "native_ios",
    "swiftui": "native_ios",
    "uikit": "native_ios",
    "ios": "native_ios",
    "appstore": "native_ios",
    "javascript": "web_frontend",
    "typescript": "web_frontend",
    "react": "web_frontend",
    "next.js": "web_frontend",
    "vue.js": "web_frontend",
    "angular": "web_frontend",
    "svelte": "web_frontend",
    "redux": "web_frontend",
    "rxjs": "web_frontend",
    "ngrx": "web_frontend",
    "html": "web_frontend",
    "css": "web_frontend",
    "scss": "web_frontend",
    "tailwindcss": "web_frontend",
    "bootstrap": "web_frontend",
    "webpack": "web_frontend",
    "vite": "web_frontend",
    "graphql": "web_frontend",
    "python": "backend_python",
    "django": "backend_python",
    "djangorestframework": "backend_python",
    "fastapi": "backend_python",
    "flask": "backend_python",
    "celery": "backend_python",
    "pytest": "backend_python",
    "node.js": "backend_node",
    "express": "backend_node",
    "java": "backend_java",
    "springboot": "backend_java",
    "csharp": "backend_dotnet",
    "dotnet": "backend_dotnet",
    "php": "backend_php",
    "laravel": "backend_php",
    "postgresql": "data",
    "mysql": "data",
    "mongodb": "data",
    "redis": "data",
    "kafka": "data",
    "etl": "data",
    "airflow": "data",
    "spark": "data",
    "hadoop": "data",
    "datapipeline": "data",
    "datawarehouse": "data",
    "datamodeling": "data",
    "snowflake": "data",
    "bigquery": "data",
    "redshift": "data",
    "tableau": "data",
    "powerbi": "data",
    "looker": "data",
    "excel": "data",
    "statistics": "data",
    "probability": "data",
    "dashboarding": "data",
    "reporting": "data",
    "dataanalysis": "data",
    "datacleaning": "data",
    "datavisualization": "data",
    "pandas": "ml_data",
    "numpy": "ml_data",
    "matplotlib": "ml_data",
    "seaborn": "ml_data",
    "r": "ml_data",
    "machinelearning": "ml_data",
    "deeplearning": "ml_data",
    "nlp": "ml_data",
    "computervision": "ml_data",
    "llm": "ml_data",
    "faiss": "ml_data",
    "tensorflow": "ml_data",
    "pytorch": "ml_data",
    "keras": "ml_data",
    "scikitlearn": "ml_data",
    "featureengineering": "ml_data",
    "mlops": "ml_data",
    "modeldeployment": "ml_data",
    "kubernetes": "devops",
    "helm": "devops",
    "terraform": "devops",
    "ansible": "devops",
    "jenkins": "devops",
    "prometheus": "devops",
    "grafana": "devops",
    "elkstack": "devops",
    "aws": "devops",
    "azure": "devops",
    "gcp": "devops",
    "networksecurity": "security",
    "firewall": "security",
    "idsips": "security",
    "penetrationtesting": "security",
    "ethicalhacking": "security",
    "siem": "security",
    "riskassessment": "security",
    "compliance": "security",
    "cissp": "security",
    "cryptography": "security",
    "securityauditing": "security",
    "figma": "ux_design",
    "sketch": "ux_design",
    "adobexd": "ux_design",
    "uidesign": "ux_design",
    "uxdesign": "ux_design",
    "wireframing": "ux_design",
    "prototyping": "ux_design",
    "usabilitytesting": "ux_design",
    "interactiondesign": "ux_design",
    "informationarchitecture": "ux_design",
    "designsystems": "ux_design",
    "userflows": "ux_design",
    "personas": "ux_design",
    "userresearch": "ux_design",
    "photoshop": "graphic_design",
    "illustrator": "graphic_design",
    "indesign": "graphic_design",
    "typography": "graphic_design",
    "colortheory": "graphic_design",
    "canva": "graphic_design",
    "branding": "graphic_design",
    "logos": "graphic_design",
    "printdesign": "graphic_design",
    "visualdesign": "graphic_design",
    "layout": "graphic_design",
    "productstrategy": "product",
    "roadmapping": "product",
    "marketresearch": "product",
    "productmetrics": "product",
    "confluence": "product",
    "notion": "product",
    "seo": "marketing",
    "sem": "marketing",
    "contentstrategy": "marketing",
    "socialmedia": "marketing",
    "googleanalytics": "marketing",
    "emailmarketing": "marketing",
    "marketingautomation": "marketing",
    "hubspot": "marketing",
    "growthstrategy": "marketing",
    "campaignmanagement": "marketing",
    "brandstrategy": "marketing",
    "digitalmarketing": "marketing",
    "crm": "marketing",
    "accounting": "finance",
    "bookkeeping": "finance",
    "quickbooks": "finance",
    "xero": "finance",
    "taxpreparation": "finance",
    "financialreporting": "finance",
    "gaap": "finance",
    "auditing": "finance",
    "financialanalysis": "finance",
    "erp": "finance",
    "sap": "finance",
    "oraclefinancials": "finance",
    "payroll": "finance",
    "recruiting": "hr",
    "onboarding": "hr",
    "employeerelations": "hr",
    "hrpolicies": "hr",
    "hris": "hr",
    "performancemanagement": "hr",
    "benefitsadministration": "hr",
    "laborlaws": "hr",
    "talentacquisition": "hr",
    "ats": "hr",
}

# Skills that are relevant regardless of stack (required by jobs everywhere).
FAMILY_UNIVERSAL = {
    "git", "sql", "rest", "restapi", "restapis", "restfulapi", "apidesign",
    "apidevelopment", "unittesting", "tdd", "cicd", "githubactions", "docker",
    "linux", "shellscripting", "debugging", "oop", "designpatterns",
    "algorithms", "datastructures", "communication", "collaboration",
    "teamwork", "problemsolving", "criticalthinking", "timemanagement",
    "adaptability", "leadership", "postman", "jira", "agile", "scrum",
    "yaml", "vscode",
}

# Families considered genuinely related to each other.
FAMILY_ADJACENCY = {
    "backend_python": {"backend_node", "backend_java", "backend_dotnet", "backend_php", "devops", "ml_data"},
    "backend_node": {"backend_python", "backend_java", "backend_dotnet", "backend_php", "devops"},
    "backend_java": {"backend_python", "backend_node", "backend_dotnet", "backend_php", "devops"},
    "backend_dotnet": {"backend_python", "backend_node", "backend_java", "backend_php", "devops"},
    "backend_php": {"backend_python", "backend_node", "backend_java", "backend_dotnet", "devops"},
    "data": {"ml_data"},
    "ml_data": {"data", "backend_python", "devops"},
    "devops": {"security", "backend_python", "backend_java", "backend_node"},
    "security": {"devops"},
    "ux_design": {"graphic_design"},
    "graphic_design": {"ux_design"},
}


def stack_relevant_families(user_skills_norm):
    """Families relevant to the candidate's detected stack: their own skill
    families plus declared adjacent families."""
    families = set()
    for key in user_skills_norm:
        family = SKILL_FAMILIES.get(key)
        if family:
            families.add(family)
            families.update(FAMILY_ADJACENCY.get(family, set()))
    return families


def is_skill_relevant(skill_key, user_skills_norm):
    """True when a missing skill belongs to the candidate's stack families,
    a universal skill, or the candidate has no detectable stack (no filter)."""
    families = stack_relevant_families(user_skills_norm)
    if not families:
        return True
    family = SKILL_FAMILIES.get(skill_key)
    if family is None:
        return skill_key in FAMILY_UNIVERSAL
    return family in families or skill_key in FAMILY_UNIVERSAL


_catalog_cache = None


def _load_catalog():
    path = settings.DATA_DIR / "course_catalog.json"
    if not path.exists():
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {normalize_skill(key): entry for key, entry in raw.items()}


def get_catalog():
    global _catalog_cache
    if _catalog_cache is None:
        _catalog_cache = _load_catalog()
    return _catalog_cache


def get_course_entry(skill):
    return get_catalog().get(normalize_skill(skill))


def get_skill_difficulty(skill):
    key = normalize_skill(skill)
    if key in DIFFICULTY_OVERRIDES:
        return DIFFICULTY_OVERRIDES[key]
    entry = get_course_entry(key)
    if entry:
        return entry.get("difficulty") or DEFAULT_DIFFICULTY
    return DEFAULT_DIFFICULTY


def get_skill_dependencies(skill):
    key = normalize_skill(skill)
    return list(SKILL_DEPENDENCIES.get(key, []))


_display_cache = None


def display_for_key(key):
    global _display_cache
    if _display_cache is None:
        _display_cache = dict(DISPLAY_OVERRIDES)
        for config in PROFESSION_CONFIGS.values():
            for name in config.get("skills", {}):
                _display_cache.setdefault(normalize_skill(name), name)
    return _display_cache.get(key, display_name(key))
