# Generated by Django 6.0.6 on 2026-06-18 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('education', models.TextField(blank=True, help_text='Use separate lines for education entries.')),
                ('skills', models.TextField(blank=True, help_text='Use commas or lines to separate skills.')),
                ('work_experience', models.TextField(blank=True, help_text='Use separate lines for each experience entry.')),
                ('projects', models.TextField(blank=True, help_text='Use separate lines for each project entry.')),
                ('certifications', models.TextField(blank=True, help_text='Use separate lines for each certification.')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('profile_photo', models.FileField(blank=True, help_text='Optional profile photo for records only.', null=True, upload_to='cv_profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
