# Generated by Django 4.2 on 2026-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='selected_template',
            field=models.CharField(choices=[('modern', 'Modern'), ('professional', 'Professional'), ('minimal', 'Minimal'), ('executive', 'Executive'), ('creative', 'Creative'), ('elegant', 'Elegant'), ('corporate', 'Corporate'), ('ats_friendly', 'ATS Friendly'), ('classic', 'Classic'), ('compact', 'Compact')], default='modern', help_text='The CV template last chosen for this profile.', max_length=50),
        ),
    ]
