# Generated by Django 4.2 on 2026-08-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvgen', '0003_alter_jobseekerprofile_projects_additionalinfoentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='projects',
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name, e.g. "Cyber Scam Detection System".', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Use separate lines for each point (technologies, description, impact, etc.).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cvgen.jobseekerprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. "Bachelor of Software Engineering" or "Master of Business Administration".', max_length=255)),
                ('institution', models.CharField(blank=True, help_text='School or university name.', max_length=255)),
                ('year', models.CharField(blank=True, help_text='e.g. "2020 - 2024" or "Expected 2026".', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cvgen.jobseekerprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
